#!/bin/bash
# create-feedback-schema.sh - Create PostgreSQL schema for feedback pipeline
#
# Creates 3 tables for the test feedback pipeline:
#   - test_results: Journey test execution results
#   - feedback: Persona feedback from test runs
#   - issues: Prioritized issues from feedback analysis
#
# Usage:
#   ./create-feedback-schema.sh              # Uses default credentials
#   POSTGRES_PASSWORD=xxx ./create-feedback-schema.sh

set -e

PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"
NAMESPACE="${NAMESPACE:-$(basename "$PROJECT_ROOT")}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=== Creating Feedback Pipeline Schema ==="
echo ""

# Load credentials from .env if exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo "Loading credentials from .env..."
    set -a
    source "$PROJECT_ROOT/.env"
    set +a
fi

# Try K8s secrets if not in .env
if [ -z "$POSTGRES_PASSWORD" ]; then
    echo "Attempting to get credentials from Kubernetes..."
    POSTGRES_PASSWORD=$(kubectl get secret postgres-credentials -n "$NAMESPACE" \
        -o jsonpath='{.data.POSTGRES_PASSWORD}' 2>/dev/null | base64 -d || echo "")
fi

# Set defaults
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-$NAMESPACE}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"

if [ -z "$POSTGRES_PASSWORD" ]; then
    echo -e "${YELLOW}Warning: No POSTGRES_PASSWORD found${NC}"
    echo "Will attempt connection without password (may fail)"
fi

echo "Database: $POSTGRES_DB@$POSTGRES_HOST:$POSTGRES_PORT"
echo ""

# Wait for PostgreSQL to be ready
echo "Waiting for PostgreSQL..."
MAX_RETRIES=30
RETRY_COUNT=0
while ! PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 1" > /dev/null 2>&1; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
        echo -e "${RED}Error: PostgreSQL not ready after $MAX_RETRIES attempts${NC}"
        exit 1
    fi
    echo "  Waiting... ($RETRY_COUNT/$MAX_RETRIES)"
    sleep 2
done
echo -e "${GREEN}PostgreSQL is ready${NC}"
echo ""

# Create tables
echo "Creating feedback tables..."
PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<'EOF'

-- =============================================================================
-- FEEDBACK PIPELINE TABLES (v1.0)
-- =============================================================================
-- These tables support the test feedback pipeline:
--   test-journey -> generate-feedback -> analyze-feedback -> research -> fix
-- =============================================================================

-- test_results: Journey test execution results from /pm:test-journey
CREATE TABLE IF NOT EXISTS test_results (
    id SERIAL PRIMARY KEY,
    session_name VARCHAR(255) NOT NULL,
    test_run_id VARCHAR(50) NOT NULL,
    journey_id INTEGER,
    persona_id VARCHAR(50),
    base_url VARCHAR(500),
    overall_status VARCHAR(20) CHECK (overall_status IN ('pass', 'fail', 'partial')),
    steps_passed INTEGER DEFAULT 0,
    steps_failed INTEGER DEFAULT 0,
    step_results JSONB DEFAULT '[]',
    issues_found JSONB DEFAULT '[]',
    screenshots_count INTEGER DEFAULT 0,
    executed_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (session_name, test_run_id, journey_id, persona_id)
);

COMMENT ON TABLE test_results IS 'Journey test execution results from /pm:test-journey';
COMMENT ON COLUMN test_results.test_run_id IS 'Groups results from same test execution, format: run-YYYYMMDD-HHMMSS';
COMMENT ON COLUMN test_results.step_results IS 'JSONB array: [{step_number, status, observation}]';
COMMENT ON COLUMN test_results.issues_found IS 'JSONB array: [{step_number, description}]';

CREATE INDEX IF NOT EXISTS idx_test_results_session ON test_results(session_name);
CREATE INDEX IF NOT EXISTS idx_test_results_run ON test_results(session_name, test_run_id);
CREATE INDEX IF NOT EXISTS idx_test_results_journey ON test_results(journey_id);

-- feedback: Persona feedback from test runs, generated by /pm:generate-feedback
CREATE TABLE IF NOT EXISTS feedback (
    id SERIAL PRIMARY KEY,
    session_name VARCHAR(255) NOT NULL,
    test_run_id VARCHAR(50) NOT NULL,
    persona_id VARCHAR(50) NOT NULL,
    overall_rating INTEGER CHECK (overall_rating BETWEEN 1 AND 5),
    nps_score INTEGER CHECK (nps_score BETWEEN 0 AND 10),
    recommendation VARCHAR(20) CHECK (recommendation IN ('yes', 'no', 'maybe')),
    positives JSONB DEFAULT '[]',
    frustrations JSONB DEFAULT '[]',
    bugs JSONB DEFAULT '[]',
    feature_requests JSONB DEFAULT '[]',
    test_context JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (session_name, test_run_id, persona_id)
);

COMMENT ON TABLE feedback IS 'Persona feedback from test runs, generated by /pm:generate-feedback';
COMMENT ON COLUMN feedback.test_run_id IS 'Links to test_results from same run';
COMMENT ON COLUMN feedback.frustrations IS 'JSONB array: [{theme, severity, journey_ref}]';
COMMENT ON COLUMN feedback.bugs IS 'JSONB array: [{title, description, severity, steps_to_reproduce}]';
COMMENT ON COLUMN feedback.feature_requests IS 'JSONB array: [{title, description, priority}]';

CREATE INDEX IF NOT EXISTS idx_feedback_session ON feedback(session_name);
CREATE INDEX IF NOT EXISTS idx_feedback_run ON feedback(session_name, test_run_id);
CREATE INDEX IF NOT EXISTS idx_feedback_persona ON feedback(persona_id);

-- issues: Prioritized issues from feedback analysis, generated by /pm:analyze-feedback
CREATE TABLE IF NOT EXISTS issues (
    id SERIAL PRIMARY KEY,
    session_name VARCHAR(255) NOT NULL,
    test_run_id VARCHAR(50) NOT NULL,
    issue_id VARCHAR(50),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(50) CHECK (category IN ('bug', 'ux', 'performance', 'feature_request')),
    severity VARCHAR(20) CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    mentions INTEGER DEFAULT 1,
    rice_score DECIMAL(10,2),
    journey_refs JSONB DEFAULT '[]',
    persona_refs JSONB DEFAULT '[]',
    research_context TEXT,
    fix_attempts INTEGER DEFAULT 0,
    resolved_at TIMESTAMPTZ,
    status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'triaged', 'prd_created', 'resolved', 'escalated')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (session_name, test_run_id, issue_id)
);

COMMENT ON TABLE issues IS 'Prioritized issues from feedback analysis, generated by /pm:analyze-feedback';
COMMENT ON COLUMN issues.test_run_id IS 'Links to feedback from same run';
COMMENT ON COLUMN issues.issue_id IS 'External ID like I-001 for documentation';
COMMENT ON COLUMN issues.rice_score IS 'RICE prioritization score: (Reach * Impact * Confidence) / Effort';
COMMENT ON COLUMN issues.journey_refs IS 'JSONB array of related journey IDs';
COMMENT ON COLUMN issues.persona_refs IS 'JSONB array of personas who reported this issue';
COMMENT ON COLUMN issues.research_context IS 'Deep research findings for fixing this issue';
COMMENT ON COLUMN issues.fix_attempts IS 'Number of automated fix attempts made';
COMMENT ON COLUMN issues.resolved_at IS 'Timestamp when issue was resolved';
COMMENT ON COLUMN issues.status IS 'Status: open, triaged (researched), prd_created, resolved, escalated (fix failed)';

CREATE INDEX IF NOT EXISTS idx_issues_session ON issues(session_name);
CREATE INDEX IF NOT EXISTS idx_issues_run ON issues(session_name, test_run_id);
CREATE INDEX IF NOT EXISTS idx_issues_severity ON issues(severity);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(session_name, status);

EOF

# Verify tables
echo ""
echo "Verifying tables..."
TABLES=("test_results" "feedback" "issues")
MISSING=0

for TABLE in "${TABLES[@]}"; do
    EXISTS=$(PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" \
        -U "$POSTGRES_USER" -d "$POSTGRES_DB" -t -c \
        "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = '$TABLE'" | tr -d ' ')
    if [ "$EXISTS" -eq 0 ] 2>/dev/null; then
        echo -e "  ${RED}x $TABLE${NC}"
        MISSING=$((MISSING + 1))
    else
        echo -e "  ${GREEN}v $TABLE${NC}"
    fi
done

echo ""
if [ $MISSING -eq 0 ]; then
    echo -e "${GREEN}Feedback schema ready: 3 tables${NC}"
else
    echo -e "${RED}Missing $MISSING tables${NC}"
    exit 1
fi
